# -*- coding: utf-8 -*-
"""Metode Desicion Tree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BsxF5toXBRXnS2LomJO40Ry-Bg2oKQIO
"""

from sklearn import tree

# Database: Gerbang logika AND
# x = Data, Y = Target
x = [[0,0], [0,1], [1,0], [1,1], [0,6], [6,0], [6,6], [0,7], [7,0], [7,7]]
y = [0,0,0,1,0,0,1,0,0,1]

# Training and Classify
clf = tree.DecisionTreeClassifier()
clf = clf.fit(x,y)

# Prediksi
print ("Logika AND Metode Desicion Tree")
print ("Logika = Prediksi")
print ("0 0 = ", clf.predict([[0,0]]))
print ("0 1 = ", clf.predict([[0,1]]))
print ("1 0 = ", clf.predict([[1,0]]))
print ("1 1 = ", clf.predict([[1,1]]))
print ("0 6 = ", clf.predict([[0,6]]))
print ("6 0 = ", clf.predict([[6,0]]))
print ("6 6 = ", clf.predict([[6,6]]))
print ("0 7 = ", clf.predict([[0,7]]))
print ("7 0 = ", clf.predict([[7,0]]))
print ("7 7 = ", clf.predict([[7,7]]))
